import * as fs from 'fs';
import * as path from 'path';
import type { SkillDefinition } from './types.js';

export const SKILL_REGISTRY: SkillDefinition[] = [
  // ── 内置技能 (10) ──────────────────────────────────────────
  {
    id: 'search',
    name: '网络搜索',
    description: '实时联网搜索，附来源引用',
    trigger: '/search',
    icon: '🔍',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'search/SKILL.md',
  },
  {
    id: 'pdf',
    name: 'PDF 工具',
    description: 'PDF 文档读取、提取、摘要与转换',
    trigger: '/pdf',
    icon: '📄',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'pdf/SKILL.md',
  },
  {
    id: 'code',
    name: '代码助手',
    description: '写代码、解释代码、Debug',
    trigger: '/code',
    icon: '💻',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'code/SKILL.md',
  },
  {
    id: 'tell-me',
    name: '飞书通知',
    description: '总结对话并推送到飞书群',
    trigger: '/tell-me',
    icon: '💬',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'tell-me/SKILL.md',
  },
  {
    id: 'scheduler',
    name: '定时任务',
    description: '定时执行任务（提醒、汇总）',
    trigger: '/scheduler',
    icon: '⏰',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'scheduler/SKILL.md',
  },
  {
    id: 'browser',
    name: '浏览器',
    description: '打开网页、截图、填表、提取内容',
    trigger: '/browser',
    icon: '🌐',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: ['playwright'],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'browser/SKILL.md',
  },
  {
    id: 'pptx',
    name: 'PPT 工具',
    description: '创建、编辑和分析演示文稿',
    trigger: '/pptx',
    icon: '📊',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'pptx/SKILL.md',
  },
  {
    id: 'xlsx',
    name: '表格工具',
    description: '电子表格创建、数据分析与可视化',
    trigger: '/xlsx',
    icon: '📈',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'xlsx/SKILL.md',
  },
  {
    id: 'docx',
    name: '文档工具',
    description: 'Word 文档创建、编辑与格式化',
    trigger: '/docx',
    icon: '📝',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'docx/SKILL.md',
  },
  {
    id: 'skill-installer',
    name: '技能安装器',
    description: '从策展仓库安装社区技能',
    trigger: '/skill-installer',
    icon: '📦',
    category: 'builtin',
    builtin: true,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'skill-installer/SKILL.md',
  },

  // ── 市场技能 · 效率工具 (6) ────────────────────────────────
  {
    id: 'briefing',
    name: '每日简报',
    description: '早间天气、日历、待办、热点摘要',
    trigger: '/briefing',
    icon: '📰',
    category: 'productivity',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'briefing/SKILL.md',
  },
  {
    id: 'todo',
    name: '待办管理',
    description: '创建/查看/完成待办事项，支持提醒',
    trigger: '/todo',
    icon: '✅',
    category: 'productivity',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'todo/SKILL.md',
  },
  {
    id: 'remember',
    name: '记忆笔记',
    description: '让 AI 记住偏好/信息，跨会话召回',
    trigger: '/remember',
    icon: '🧠',
    category: 'productivity',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'remember/SKILL.md',
  },
  {
    id: 'meeting-notes',
    name: '会议纪要',
    description: '文字转会议摘要、待办提取',
    trigger: '/meeting-notes',
    icon: '📋',
    category: 'productivity',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'meeting-notes/SKILL.md',
  },
  {
    id: 'weekly-report',
    name: '周报生成',
    description: '基于本周对话/待办自动生成周报',
    trigger: '/weekly-report',
    icon: '📅',
    category: 'productivity',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'weekly-report/SKILL.md',
  },
  {
    id: 'project-mgmt',
    name: '项目管理',
    description: '多任务看板、进度追踪',
    trigger: '/project-mgmt',
    icon: '🗂',
    category: 'productivity',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'project-mgmt/SKILL.md',
  },

  // ── 市场技能 · 内容创作 (4) ────────────────────────────────
  {
    id: 'write',
    name: '写作助手',
    description: '邮件、朋友圈、工作汇报等文案生成',
    trigger: '/write',
    icon: '✍️',
    category: 'content',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'write/SKILL.md',
  },
  {
    id: 'xiaohongshu',
    name: '小红书文案',
    description: '爆款标题 + 内容 + 标签生成',
    trigger: '/xiaohongshu',
    icon: '📕',
    category: 'content',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'xiaohongshu/SKILL.md',
  },
  {
    id: 'copywriting',
    name: '文案润色',
    description: '语法修正、风格调整、降 AI 感',
    trigger: '/copywriting',
    icon: '✨',
    category: 'content',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'copywriting/SKILL.md',
  },
  {
    id: 'resume',
    name: '简历优化',
    description: '针对岗位优化简历内容和措辞',
    trigger: '/resume',
    icon: '💼',
    category: 'content',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'resume/SKILL.md',
  },

  // ── 市场技能 · 学习知识 (3) ────────────────────────────────
  {
    id: 'vocabulary',
    name: '单词本',
    description: 'AI 语境造句、间隔重复',
    trigger: '/vocabulary',
    icon: '📚',
    category: 'learning',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'vocabulary/SKILL.md',
  },
  {
    id: 'mock-interview',
    name: '面试模拟',
    description: '模拟面试官，出题 + 点评',
    trigger: '/mock-interview',
    icon: '🎤',
    category: 'learning',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'mock-interview/SKILL.md',
  },
  {
    id: 'paper-reader',
    name: '论文解读',
    description: '学术论文快速解读和要点提取',
    trigger: '/paper-reader',
    icon: '🎓',
    category: 'learning',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'paper-reader/SKILL.md',
  },

  // ── 市场技能 · 生活服务 (2) ────────────────────────────────
  {
    id: 'travel-planner',
    name: '旅行规划',
    description: '行程安排、预算、注意事项',
    trigger: '/travel-planner',
    icon: '✈️',
    category: 'lifestyle',
    builtin: false,
    readiness: 'L2',
    deps: ['maps-api'],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'travel-planner/SKILL.md',
  },
  {
    id: 'recipe',
    name: '菜谱推荐',
    description: '根据现有食材推荐菜谱 + 步骤',
    trigger: '/recipe',
    icon: '🍳',
    category: 'lifestyle',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'recipe/SKILL.md',
  },

  // ── 市场技能 · 开发工具 (4) ────────────────────────────────
  {
    id: 'skill-creator',
    name: '技能创建',
    description: '引导创建自定义技能',
    trigger: '/skill-creator',
    icon: '🔧',
    category: 'devtools',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'skill-creator/SKILL.md',
  },
  {
    id: 'git-helper',
    name: 'Git 助手',
    description: 'commit message、PR 描述、冲突解决',
    trigger: '/git-helper',
    icon: '🔀',
    category: 'devtools',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'git-helper/SKILL.md',
  },
  {
    id: 'sql-helper',
    name: 'SQL 助手',
    description: '自然语言转 SQL，查询优化',
    trigger: '/sql-helper',
    icon: '🗃',
    category: 'devtools',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'sql-helper/SKILL.md',
  },
  {
    id: 'api-debug',
    name: 'API 调试',
    description: '构造请求、解析响应、生成文档',
    trigger: '/api-debug',
    icon: '🔌',
    category: 'devtools',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'api-debug/SKILL.md',
  },

  // ── 市场技能 · 研究分析 (1) ────────────────────────────────
  {
    id: 'data-analysis',
    name: '数据分析',
    description: 'CSV/表格数据分析 + 可视化',
    trigger: '/data-analysis',
    icon: '📉',
    category: 'research',
    builtin: false,
    readiness: 'L1',
    deps: [],
    riskLevel: 'low',
    defaultEnabled: true,
    owner: 'system',
    mdPath: 'data-analysis/SKILL.md',
  },
];

export function getBuiltinSkills(): SkillDefinition[] {
  return SKILL_REGISTRY.filter(s => s.builtin);
}

export function getMarketSkills(): SkillDefinition[] {
  return SKILL_REGISTRY.filter(s => !s.builtin);
}

export function getSkillById(id: string): SkillDefinition | undefined {
  return SKILL_REGISTRY.find(s => s.id === id);
}

export function getSkillsByCategory(category: string): SkillDefinition[] {
  return SKILL_REGISTRY.filter(s => s.category === category);
}

export function getReadySkills(): SkillDefinition[] {
  return SKILL_REGISTRY.filter(s => s.readiness === 'L1');
}

export function getIconForSkill(id: string): string {
  return getSkillById(id)?.icon ?? '⚡';
}

export function validateRegistry(catalogBasePath: string): string[] {
  const errors: string[] = [];
  for (const skill of SKILL_REGISTRY) {
    const mdFile = path.join(catalogBasePath, skill.mdPath);
    if (!fs.existsSync(mdFile)) {
      errors.push(`[MISSING] ${skill.id}: ${mdFile}`);
    }
  }
  return errors;
}
